services:
  bank-api:
    container_name: bank_api
    image: viniciusfk/bank-api:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://internal_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - internal-db

  internal-db:
    container_name: internal_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - internaldb:/var/lib/postgresql/data

volumes:
  internaldb: {}